### PR TITLE
Small bug

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
Any particular reason for making a second / new PR instead of adding changes to #105?

**Comment by IanEisenberg** [comment]
Not really. I just kept them separate because they are dealing with
separate issues and wanted to keep the validation PR specific because that
one is more important.

On Tuesday, April 5, 2016, Vanessa Sochat notifications@github.com wrote:

> Any particular reason for making a second / new PR instead of adding
> changes to #105 https://github.com/expfactory/expfactory-python/pull/105
> ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-python/pull/106#issuecomment-205718063

## 

Best,
Ian

**Comment by vsoch** [comment]
This branch also includes the validation PR, so they are not separate. You have to checkout a new branch from master to do this correctly.

**Comment by IanEisenberg** [comment]
Ah yeah! My bad. Should I just include this on the validation pr or check
out from master? This one I didn't know how to test really so it was more
to just alert you of this potential issue, expecting the pr to be closed
rather than merged

On Tuesday, April 5, 2016, Vanessa Sochat notifications@github.com wrote:

> This branch also includes the validation PR, so they are not separate. You
> have to checkout a new branch from master to do this correctly.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-python/pull/106#issuecomment-205874727

## 

Best,
Ian

**Comment by vsoch** [comment]
No worries! Sometimes people open new PRs and close the previous and I wanted to make sure this was not the case. Just leave both as is and I will take care of when I review later today.

**Pull request closed without merging**
