### PR TITLE
updated validation to not use question name

### PR DESCRIPTION
**Pull request by IanEisenberg**
Changing validation to not use names so that expfactory/expfactory-surveys#50 can be addressed. The validation now uses the shared meta-text

### CODE REVIEW

**Comment by IanEisenberg** [comment]
New validation:

`validation = "%s if (($.unique($('.page%s.required[type=number],.page%s.required:text').map(function(){return $(this).attr('meta-text')})).map(function() {return $('[meta-text*="' + this + '"].required[type=number], [meta-text*="' + this + '"].required:text').filter(function() { return $(this).val();}).length > 0}).get().indexOf(false) != -1) || ($.unique($('.page%s.required:not([type=number]):not(:text)').map(function(){return $(this).attr('meta-text')})).map(function() {return $('[meta-text*="' + this + '"].required:checked').length > 0}).get().indexOf(false) != -1))
{\nis_required($('.page%s.required:not(checked)'));\nreturn false;\n" % (validation, page_number, page_number, page_number)`

**Comment by vsoch** [comment]
Does not work

image

**Comment by IanEisenberg** [comment]
Ignore this for a moment, still not working.

**Comment by IanEisenberg** [comment]
actually it was a problem with questionnaire strings sometimes containing '' marks, so now I've used ` and " because python adds in \'s to escape quotations when using triple quote syntax, which wouldn't work for javascript! This should work...I think

**Comment by vsoch** [comment]
What about the case when the text has single quotes, eg ' ?

**Comment by vsoch** [comment]
ok, since it is clear we need to be able to test the proper function of every survey, I think we need the robot to step through these and confirm making it to the end of each.

**Comment by IanEisenberg** [comment]
I tested this function with three types of quotes in the meta-text (question) string: ", ', and `. It works with all of them. Robot testing would be good too

**Comment by vsoch** [comment]
@IanEisenberg could you please rebase with master? I now have a survey robot to test this new change.

**Comment by IanEisenberg** [comment]
Done.

On Sat, May 7, 2016 at 11:25 AM, Vanessa Sochat notifications@github.com
wrote:

> @IanEisenberg https://github.com/IanEisenberg could you please rebase
> with master? I now have a survey robot to test this new change.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-python/pull/116#issuecomment-217660162

## 

Best,
Ian

**Comment by vsoch** [comment]
Ty!

**Comment by vsoch** [comment]
Ok, I've tested all surveys with the new validation, and was able to make the name change to ensure that the checkboxes have unique names, eg:

```
  {"name":"demographics_survey_6_0_options","value":"American Indian or Alaska Native","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
  {"name":"demographics_survey_6_1_options","value":"Asian","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
  {"name":"demographics_survey_6_2_options","value":"Black or African American","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
  {"name":"demographics_survey_6_3_options","value":"Native Hawaiian or Other Pacific Islander","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
  {"name":"demographics_survey_6_4_options","value":"White","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
  {"name":"demographics_survey_6_5_options","value":"Choose not to respond","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"}
```

After this is merged, I will update expfactory on expfactory.org, and we will want to immediately test taking a survey, and seeing if all checkbox responses are represented in the results. The unique names should ensure that they are.

**Comment by IanEisenberg** [comment]
I will be ready to test whenever you tell me.

On Sat, May 7, 2016 at 1:35 PM, Vanessa Sochat notifications@github.com
wrote:

> Ok, I've tested all surveys with the new validation, and was able to make
> the name change to ensure that the checkboxes have unique names, eg:
> 
>   {"name":"demographics_survey_6_0_options","value":"American Indian or Alaska Native","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
>   {"name":"demographics_survey_6_1_options","value":"Asian","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
>   {"name":"demographics_survey_6_2_options","value":"Black or African American","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
>   {"name":"demographics_survey_6_3_options","value":"Native Hawaiian or Other Pacific Islander","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
>   {"name":"demographics_survey_6_4_options","value":"White","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"},
>   {"name":"demographics_survey_6_5_options","value":"Choose not to respond","options":"American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White|Choose not to respond|Other","text":"What is your race?"}
> 
> After this is merged, I will update expfactory on expfactory.org, and we
> will want to immediately test taking a survey, and seeing if all checkbox
> responses are represented in the results. The unique names should ensure
> that they are.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-python/pull/116#issuecomment-217667196

## 

Best,
Ian

**Pull request closed without merging**
