### PR TITLE
Update for Python 3

### PR DESCRIPTION
**Pull request by vsoch**
Hey @rwblair - I started to update the expfactory-docker image (django needs a version update) and realized we need expfactory with python 3. I think one of the contributors started working on this back in 2016 and said he would PR, but never got around to it. What I've done here is (most of the work I think?) to fix up print statements, etc.

And I'm just realizing now that the circle ci needs updating too (still version 1!) I'll start working on that, and test for Python 2 and 3.

### CODE REVIEW

**Comment by rwblair** [comment]
@vsoch nice, this will be useful for sure. I'm working on upgrading expfactory-docker to use boto3 where necessary since the api that boto 2 uses is being deprecated. Was going to start in on the python 3 and django 2+ upgrade some time later this year. 

I also need to upgrade the entire cognitve atlas site as well before new years which might be an undertaking since it will involve a major neo4j upgrade. Fortunately the cognitveatlas python api library shouldn't be too terrible to get going in python 3.

**Comment by vsoch** [comment]
I can help with both! :) I'm working on a new circle recipe for testing now.

**Comment by vsoch** [comment]
oup, just hit a python 2 bug in expfactory as a result of cognitive atlas - going to update that first!

**Comment by rwblair** [comment]
Let me know if the cognitive atlas library upgrade ends up not being compatible with python2.7 anymore, I might need to go set explicit versions on a few projects (which I should of been doing already.)

**Comment by vsoch** [comment]
@rwblair the testing is set up and working, I'd like to propose leaving this open while work on expfactory-docker is done - I'll install from this branch (and update to it) if I hit any issues with the updates.

**Comment by vsoch** [comment]
good news! I just got expfactory-docker running, and instead of printing issues with cogat or expfactory due to python versions, it's all just updating the code in expfactory-docker (woohoo!) So it should be pretty easy to update everything for Python 3 - I haven't run yet today and it's almost 7pm so I'm going to do that and pick up on this likely tomorrow. Solid work today @rwblair !

**Comment by vsoch** [comment]
hey @rwblair I'm done with these early fixes, let me know when you want to discuss! Have an eggcellent Friday!

**Comment by vsoch** [comment]
Oh, here are the different database options for `on_delete` in case you need them:
https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.ForeignKey.on_delete

**Comment by vsoch** [comment]
@rwblair I'm about to push (version 2) update for expfactory, so it's good time to test pushing this version first.

**Comment by vsoch** [comment]
Ah this is very cool! We can push version 1 expfactory to pypi, and it fits right in nicely to where it should be! See the release for python 3 here https://pypi.org/project/expfactory/2.5.47/

**Comment by rwblair** [comment]
@vsoch Nice! I'll be sure to test it out when I get a chance, and pin requirements.txt accordingly

**Comment by vsoch** [comment]
Sweet! Let me know if anything is amiss and I'll get on it asap.

Holy crap, I added complete automated builds to expfactory this morning, and hit one of those "omg why didn't I specify a version" moments for psycog2. It took me like 4-5 hours to get it right! https://github.com/expfactory/expfactory/pull/120

**Pull request merged**
