### PR TITLE
changed testing behavior to only click one button_class button at a time

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by IanEisenberg** [comment]
I have no idea what selenium is (a python webbrowser module?), but I believe this should just click the random button that you had already selected.

**Comment by manbat-zz** [comment]
does this actually work? I had tried something similar and I think I had my reasons for not using button.click() - I think there was a bug with selenium when I did it this way. If you are 100% sure and have tested I will merge and push to pypi, otherwise we need to maintain doing the second command (eg, button.click()) using jquery.

**Comment by manbat-zz** [comment]
This also doesn't re-select the button after the change- I don't think this works.

**Comment by IanEisenberg** [comment]
It seemed to work when I stepped through. I can look again. An alternative is to just select a random integer in python and then use string completion to put it into a jquery call

edit: checked again. It is working fine, though I may be missing some failure point

**Comment by vsoch** [comment]
It likely worked for the regular case of pushing a button. It needs to be tested with the other case of enabling a button first then pushing it (eg the hot task)

**Comment by IanEisenberg** [comment]
Ah, of course I should have mentioned that I tested that. It seems to enable a button and then click it, no problem. It succeeds at going through the CCT_hot.

**Pull request merged**
