### PR TITLE
Validation fix

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
could you please put the code on multiple lines so it is readable?

**Comment by vsoch** [comment]
sorry I should be more specific - can you just put the final output (here is fine, if you indent 6 lines it will "codeify") so I can look at the final rendered validation code.

**Comment by IanEisenberg** [comment]
Like this? I agree, this is difficult to read.

`validation = "%s if (($.unique($('.page%s.required:text').map(function(){return this.name})).map(function() {return $('[name*=' + this + '].required:text').filter(function() { return $(this).val();}).length > 0}).get().indexOf(false) != -1) || ($.unique($('.page%s.required:not(:text)').map(function(){return this.name})).map(function() {return $('[name*=' + this + '].required:checked').length > 0}).get().indexOf(false) != -1));\nreturn false;\n" % (validation, page_number, page_number)`

**Comment by vsoch** [comment]
This PR does not work:

image

In the future please test code fully before you ask someone else to review it.

**Comment by IanEisenberg** [comment]
Sorry! There were two bugs - missing an ending "{" and a larger bug due to the change from text to number. Both should be fixed:

`"%s if (($.unique($('.page%s.required[type=number],.page3.required:text').map(function(){return this.name})).map(function() {return $('[name*=' + this + '].required[type=number], [name*=' + this + '].required:text').filter(function() { return $(this).val();}).length > 0}).get().indexOf(false) != -1) || ($.unique($('.page%s.required:not([type=number]):not(:text)').map(function(){return this.name})).map(function() {return $('[name*=' + this + '].required:checked').length > 0}).get().indexOf(false) != -1)){\nreturn false;\n" % (validation, page_number, page_number)`

Side note - I'm not actually sure how to debug effectively. I did this by creating the validator in the console with a survey open, moving it to python, adding the appropriate string completions, and testing that the string completion gave me back the working selector. Is there a way to edit expfactory-python such that I generate a webpage using the selector?

**Comment by vsoch** [comment]
As indicated by the circleCI test failing, this change still does not work:

image

Debugging means doing whatever you must do in order to test the functionality. In this case, it's pretty easy to install expfactory:

```
  sudo python setup.py install
```

and then try previewing a survey. Please test this properly and then update the PR.

**Comment by IanEisenberg** [comment]
Ah, of course. I'll try that.

On Tuesday, April 5, 2016, Vanessa Sochat notifications@github.com wrote:

> As indicated by the circleCI test failing, this change still does not work:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14300212/ca4b4f7e-fb43-11e5-9826-518e070bc5c2.png
> 
> Debugging means doing whatever you must do in order to test the
> functionality. In this case, it's pretty easy to install expfactory:
> 
>   sudo python setup.py install
> 
> and then try previewing a survey. Please test this properly and then
> update the PR.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-python/pull/105#issuecomment-206016359

## 

Best,
Ian

**Comment by vsoch** [comment]
Great! Thanks.

**Pull request closed without merging**
