### PR TITLE
Changed input type of numeric options to number to avoid from the beg…

### PR DESCRIPTION
**Pull request by zenkavi**
…inning any text input.

### CODE REVIEW

**Comment by vsoch** [comment]
have you confirmed that this works with the material design style and js? I noticed you removed the pattern variable...

**Comment by vsoch** [comment]
If you need to test, I can make the change locally, update expfactory.github.io, and then you can confirm the surveys look good - let me know.

**Comment by IanEisenberg** [comment]
This change only allows numeric input to begin with. We tested in that we changed the html and confirmed that it would only allow numbers.

**Comment by IanEisenberg** [comment]
That would be great! We have been testing in static html/changing the html. With this and the validation change it would be great to have a local change so I can go through and test.

**Comment by vsoch** [comment]
ok, give me one sec :)

**Comment by vsoch** [comment]
ok pushed, ready for you to look

**Comment by IanEisenberg** [comment]
Verified for numeric questions

**Comment by vsoch** [comment]
ok I'll need a minute to install on server

**Pull request closed without merging**
